# Generated by Django 4.0.1 on 2022-01-30 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number should be like one of theses formats: +989135556677 or 09135556677', regex='(\\+/d/d)?\\d{10,11}')], verbose_name='Phone')),
                ('home', models.CharField(blank=True, max_length=16, null=True)),
                ('work', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('other', models.CharField(blank=True, max_length=16, null=True, verbose_name='other numbers')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('emergency_contact', models.BooleanField(default=False, help_text='Call this contact in case of emergency.')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
