# Generated by Django 4.0.1 on 2022-01-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, default='null'),
            preserve_default=False,
        ),
    ]
